export const stocks = [
    {
        id: '1',
        name: 'Apple Inc.',
        symbol: 'AAPL',
        icon: 'apple-icon',
        sector: 'Technology',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 146.92,
        change: -0.23,
        changePercentage: -0.16
    },
    {
        id: '2',
        name: 'Microsoft Corporation',
        symbol: 'MSFT',
        icon: 'microsoft-icon',
        sector: 'Technology',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 300.35,
        change: +1.56,
        changePercentage: +0.52
    },
    {
        id: '3',
        name: 'Amazon.com Inc.',
        symbol: 'AMZN',
        icon: 'amazon-icon',
        sector: 'Consumer Cyclical',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 3306.37,
        change: -11.02,
        changePercentage: -0.33
    },
    {
        id: '4',
        name: 'Tesla, Inc.',
        symbol: 'TSLA',
        icon: 'tesla-icon',
        sector: 'Consumer Cyclical',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 796.22,
        change: -15.45,
        changePercentage: -1.90
    },
    {
        id: '5',
        name: 'Alphabet Inc. (Google)',
        symbol: 'GOOGL',
        icon: 'google-icon',
        sector: 'Communication Services',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 2836.93,
        change: -21.40,
        changePercentage: -0.75
    },
    {
        id: '6',
        name: 'Facebook, Inc.',
        symbol: 'FB',
        icon: 'facebook-icon',
        sector: 'Communication Services',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 339.03,
        change: -0.61,
        changePercentage: -0.18
    },
    {
        id: '7',
        name: 'Netflix, Inc.',
        symbol: 'NFLX',
        icon: 'netflix-icon',
        sector: 'Communication Services',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 585.77,
        change: -2.35,
        changePercentage: -0.40
    },
    {
        id: '8',
        name: 'NVIDIA Corporation',
        symbol: 'NVDA',
        icon: 'nvidia-icon',
        sector: 'Technology',
        country: 'United States',
        exchange: 'NASDAQ',
        price: 222.11,
        change: -1.58,
        changePercentage: -0.71
    },
    {
        id: '9',
        name: 'Alibaba Group Holding Limited',
        symbol: 'BABA',
        icon: 'alibaba-icon',
        sector: 'Consumer Cyclical',
        country: 'China',
        exchange: 'NYSE',
        price: 188.23,
        change: +2.07,
        changePercentage: +1.11
    },
    {
        id: '10',
        name: 'Walmart Inc.',
        symbol: 'WMT',
        icon: 'walmart-icon',
        sector: 'Consumer Defensive',
        country: 'United States',
        exchange: 'NYSE',
        price: 142.23,
        change: +0.65,
        changePercentage: +0.46
    },
    {
        id: '11',
        name: 'Johnson & Johnson',
        symbol: 'JNJ',
        icon: 'jnj-icon',
        sector: 'Healthcare',
        country: 'United States',
        exchange: 'NYSE',
        price: 171.58,
        change: +1.02,
        changePercentage: +0.60
    },
    {
        id: '12',
        name: 'Procter & Gamble Company',
        symbol: 'PG',
        icon: 'pg-icon',
        sector: 'Consumer Defensive',
        country: 'United States',
        exchange: 'NYSE',
        price: 144.29,
        change: +0.78,
        changePercentage: +0.54
    },
    {
        id: '13',
        name: 'JPMorgan Chase & Co.',
        symbol: 'JPM',
        icon: 'jpm-icon',
        sector: 'Financial Services',
        country: 'United States',
        exchange: 'NYSE',
        price: 152.44,
        change: +0.92,
        changePercentage: +0.61
    },
]
